version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JDBC_CONNECTION=jdbc:hsqldb:file:testdb
      - JDBC_USERNAME=sa
      - JDBC_PASSWORD=
  db:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=abc
      - MYSQL_DATABASE=test